        assertFalse("Array with null elements should fail validation",
        assertFalse("Array with wrong length should fail validation",
        assertFalse("Null array should fail validation",
        assertFalse("Empty password should fail validation",
        assertFalse("Short password should fail validation",
        assertFalse("Empty phone should fail validation",
        assertFalse("Empty email should fail validation",
        assertFalse("Invalid email should fail validation",
        assertFalse("Empty last name should fail validation",
        assertFalse("Empty first name should fail validation",
        assertTrue("All valid inputs should pass validation",
        assertTrue("Password with special characters should be valid",
        assertTrue("Password with mixed characters should be valid",
        assertTrue("Email with dots and underscores should be valid",
